workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.freegym.app"
      node: 20
      xcode: 15.0
      cocoapods: default
    
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      
      - name: Build web assets
        script: |
          npm run build:mobile
      
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      
      - name: Build ipa for development (no code signing)
        script: |
          cd ios/App
          
          # Create export options plist file
          cat > build/ExportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>development</string>
            <key>teamID</key>
            <string></string>
            <key>compileBitcode</key>
            <false/>
            <key>uploadBitcode</key>
            <false/>
            <key>uploadSymbols</key>
            <false/>
            <key>signingStyle</key>
            <string>manual</string>
            <key>signingCertificate</key>
            <string></string>
            <key>provisioningProfiles</key>
            <dict></dict>
          </dict>
          </plist>
          EOF
          
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath build/App.xcarchive \
            archive \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
          
          xcodebuild \
            -exportArchive \
            -archivePath build/App.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist build/ExportOptions.plist \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
    
    artifacts:
      - ios/App/build/ipa/*.ipa
      - ios/App/build/App.xcarchive
      - /tmp/xcodebuild_logs/*.log
    
    publishing:
      email:
        recipients:
          - theoharis@getfitskg.com
        notify:
          success: true
          failure: true
      
      # Αν θέλεις να ανεβάσει στο TestFlight (προαιρετικό)
      # app_store_connect:
      #   api_key: $APP_STORE_CONNECT_PRIVATE_KEY
      #   key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
      #   issuer_id: $APP_STORE_CONNECT_ISSUER_ID
      #   submit_to_testflight: true
      #   beta_groups:
      #     - Beta Testers

  # Δωρεάν Development Build (χωρίς code signing)
  ios-development:
    name: iOS Development Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      node: 20
      xcode: 15.0
      cocoapods: default
    
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      
      - name: Build web assets
        script: |
          npm run build:mobile
      
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      
      - name: Build for simulator (no code signing needed)
        script: |
          cd ios/App
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -sdk iphonesimulator \
            -configuration Debug \
            -derivedDataPath build
      
    artifacts:
      - ios/App/build/Build/Products/Debug-iphonesimulator/*.app

