workflows:
  # Production iOS Build για TestFlight/App Store
  ios-production:
    name: iOS Production Build (TestFlight/App Store)
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.siozostheoharis.getfit"
        APPLE_TEAM_ID: "K4A6LP6V3P"
        # App Store Connect credentials (πρόσθεσε αυτά ως Environment Variables στο Codemagic)
        APP_STORE_CONNECT_PRIVATE_KEY_ID: $APP_STORE_CONNECT_PRIVATE_KEY_ID
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
      node: 20
      xcode: 15.0
      cocoapods: default
      
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      
      - name: Build web assets
        script: |
          npm run build:mobile
      
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      
      - name: Install Cocoapods dependencies
        script: |
          cd ios/App
          pod install --repo-update
      
      - name: Build iOS App (Unsigned για τώρα)
        script: |
          cd ios/App
          
          # Build χωρίς code signing - θα δουλέψει για testing
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath build \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            PROVISIONING_PROFILE_SPECIFIER="" \
            CODE_SIGN_IDENTITY=""
      
      - name: Create IPA χειροκίνητα
        script: |
          cd ios/App
          
          # Δημιουργία .ipa χειροκίνητα από το .app
          mkdir -p build/ipa
          cp -r build/Build/Products/Release-iphoneos/App.app build/ipa/
          cd build/ipa
          zip -r App.ipa App.app
          rm -rf App.app
          
          # Επαλήθευση δημιουργίας .ipa
          ls -la App.ipa
          echo "✅ Unsigned .ipa αρχείο δημιουργήθηκε επιτυχώς!"
    
    artifacts:
      - ios/App/build/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    
    publishing:
      email:
        recipients:
          - theoharis@getfitskg.com
        notify:
          success: true
          failure: true
      
      # Αυτόματο ανέβασμα στο TestFlight (προαιρετικό - αν έχεις App Store Connect API Key)
      # app_store_connect:
      #   api_key: $APP_STORE_CONNECT_PRIVATE_KEY
      #   key_id: $APP_STORE_CONNECT_PRIVATE_KEY_ID
      #   issuer_id: $APP_STORE_CONNECT_ISSUER_ID
      #   submit_to_testflight: true
      #   beta_groups:
      #     - Beta Testers

  # Development iOS Build (για testing)
  ios-development:
    name: iOS Development Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.siozostheoharis.getfit"
        APPLE_TEAM_ID: "K4A6LP6V3P"
      node: 20
      xcode: 15.0
      cocoapods: default
      
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      
      - name: Build web assets
        script: |
          npm run build:mobile
      
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      
      - name: Install Cocoapods dependencies
        script: |
          cd ios/App
          pod install --repo-update
      
      - name: Build για iOS Simulator
        script: |
          cd ios/App
          
          # Build για iOS Simulator - το Codemagic θα χειριστεί το code signing
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -sdk iphonesimulator \
            -configuration Debug \
            -derivedDataPath build
          
          # Επαλήθευση δημιουργίας .app
          ls -la build/Build/Products/Debug-iphonesimulator/
          echo "✅ .app αρχείο δημιουργήθηκε επιτυχώς!"
    
    artifacts:
      - ios/App/build/Build/Products/Debug-iphonesimulator/*.app
    
    publishing:
      email:
        recipients:
          - theoharis@getfitskg.com
        notify:
          success: true
          failure: true

  # Unsigned iOS Build (για testing χωρίς code signing)
  ios-unsigned:
    name: iOS Unsigned Build (Testing)
    max_build_duration: 90
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.siozostheoharis.getfit"
      node: 20
      xcode: 15.0
      cocoapods: default
      
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      
      - name: Build web assets
        script: |
          npm run build:mobile
      
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      
      - name: Install Cocoapods dependencies
        script: |
          cd ios/App
          pod install --repo-update
      
      - name: Build unsigned .ipa
        script: |
          cd ios/App
          
          # Build χωρίς code signing
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath build \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            PROVISIONING_PROFILE_SPECIFIER="" \
            CODE_SIGN_IDENTITY=""
          
          # Δημιουργία .ipa χειροκίνητα
          mkdir -p build/ipa
          cp -r build/Build/Products/Release-iphoneos/App.app build/ipa/
          cd build/ipa
          zip -r App.ipa App.app
          rm -rf App.app
          
          # Επαλήθευση δημιουργίας .ipa
          ls -la App.ipa
          echo "✅ Unsigned .ipa αρχείο δημιουργήθηκε επιτυχώς!"
    
    artifacts:
      - ios/App/build/ipa/*.ipa
    
    publishing:
      email:
        recipients:
          - theoharis@getfitskg.com
        notify:
          success: true
          failure: true