workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.freegym.app"
      node: 20
      xcode: 15.0
      cocoapods: default
    
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      
      - name: Build web assets
        script: |
          npm run build:mobile
      
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      
      - name: Build .ipa without code signing (unsigned)
        script: |
          cd ios/App
          
          # Build for device without code signing
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath build \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            PROVISIONING_PROFILE_SPECIFIER="" \
            CODE_SIGN_IDENTITY=""
          
          # Create .ipa manually from .app
          mkdir -p build/ipa
          cd build/Build/Products/Release-iphoneos
          cp -r App.app build/ipa/
          cd build/ipa
          zip -r App.ipa App.app
          rm -rf App.app
    
    artifacts:
      - ios/App/build/ipa/App.ipa
      - /tmp/xcodebuild_logs/*.log
    
    publishing:
      email:
        recipients:
          - theoharis@getfitskg.com
        notify:
          success: true
          failure: true
      
      # Αν θέλεις να ανεβάσει στο TestFlight (προαιρετικό)
      # app_store_connect:
      #   api_key: $APP_STORE_CONNECT_PRIVATE_KEY
      #   key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
      #   issuer_id: $APP_STORE_CONNECT_ISSUER_ID
      #   submit_to_testflight: true
      #   beta_groups:
      #     - Beta Testers

  # Δωρεάν Development Build (χωρίς code signing)
  ios-development:
    name: iOS Development Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      node: 20
      xcode: 15.0
      cocoapods: default
    
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      
      - name: Build web assets
        script: |
          npm run build:mobile
      
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      
      - name: Build for simulator (no code signing needed)
        script: |
          cd ios/App
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -sdk iphonesimulator \
            -configuration Debug \
            -derivedDataPath build
      
    artifacts:
      - ios/App/build/Build/Products/Debug-iphonesimulator/*.app

